## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url : https://ojw28.github.io # TODO: Update to release
baseurl:  # TODO: Update to release
title   : ExoPlayer
description: An application level media player for Android


## => Link roots
##############################
releasev2: https://github.com/google/ExoPlayer/tree/release-v2
exo_sdk: /ExoPlayerDocV2/doc/reference/com/google/android/exoplayer2 # TODO: Update to release
android_sdk: https://developer.android.com/reference


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: google/ExoPlayer
repository_tree: gh-pages


## => Author and Social
##############################
author:
  type      : "organization"
  name      : "ExoPlayer"
  email     : "dev.exoplayer@gmail.com"
  github    : "google/ExoPlayer"
  medium    : "google-exoplayer"

## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
excerpt_separator: <!--more-->


## => Analytics
##############################
analytics:
  provider: google
  google:
    tracking_id : UA-68257324-1
    anonymize_ip: true


## => Search
##############################
search:
  provider: google # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: 009764199895742571316:nuhckqry2_e


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - Gemfile
  - README.md

defaults:
  - scope:
      path: ""
    values:
      footer: true
      show_date: false
      layout: article
      sidebar:
        nav: en
      aside:
        toc: false


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
